

class PFFAuthMessage(object):
    INVALID_CREDENTIALS = "Invalid Credentials! Please enter valid Credential"
    ACCOUNT_INACTIVE = "Sorry your account has been inactive."
    ACCOUNT_NOT_VERIFIED = "Sorry your account has not been verified."
    INVALID_ACCOUNT = "Invalid account."
    ERROR_ON_TOKEN_CREATION = "Unable to process authentication tokens"
    INVALID_TOKEN = "Invalid Token"
    TOKEN_EXPIRED = "Token Expired"
    TOKEN_GENERATION_ERROR = "Unable to generate token"
    OPERATOR_EXIST = "Operator already exist!"
    OPERATOR_NOT_EXIST = "Operator not exist!"
    OPERATOR_CREATE_ERROR = "Unable to create Operator!"
    OPERATOR_CREATED = "Operator has been created!"
    OPERATOR_PASS_RESET = "Operator password has been reset!"
    OPERATOR_PASS_RESET_ERROR = "Unable to reset operator password!"
    NOT_AUTHORIZE = "You are not Authorize for Access."
    PASS_RESET_REQUEST = "Password Reset Request"
    PASS_RESET_SUCCESS = "Successfully Password Reset!"
    LOGOUT_SUCCESS = "Successfully Logout"
    INVALID_TOKEN_OR_EXPIRE = "Your token is invalid or expired! Please try again."
